### ISSUE TITLE
DI as Extension Methods in Own Assemblies

### ISSUE THREAD

**Issue by SimonGeering** [DevChatter/ChatterBot#1]
Further to the fun and games on stream, I have some time to help if you have some issues to work on.

@benrick  would you like a PR that branches the DI into extension methods in the seperate assemblies and pulled out interfaces so implementation can be internal scope?

Additionally if you have a way to easily populate a DI container, such as the above extension methods, then I have a Unit Test that checks for missing DI registration in child dependencies.

**Comment by benrick** [comment]
Sure, that would make for a great PR into the project as there's not much organization to the DI yet.

**Comment by SimonGeering** [comment]
As part of PR #32 I have had to remove the package Xunit.StaFact which was an attempt to fix the problems noted int PR #17 with testing instantiation of UI elements such as a WPF Windows outside of an STA context, as would be the case with a unit test executed by a test runner. 

This brings me back to the more fundamental point raised in PR #17; 
We need to look at switching to an architecture that allows ViewModels to be instantiated by DI independently of the hosting Window, while also providing any ViewModel with a way to open child dialogs and request that their host window close etc.

This would allow checking for missing dependencies of view models as part of a PR unit test.

**Comment by benrick** [comment]
Yes, that's one of the re-work parts I need to do in order to make my [benrick/Plugin-Folder](https://github.com/DevChatter/ChatterBot/compare/benrick/Plugin-Folder) branch experiment. I've got a temporary solution in place that "works", but you'll see the problem in the [MainWindow.xaml.cs](https://github.com/DevChatter/ChatterBot/blob/cf4d5b98e75ada91cdb341d26d540d76e31c0806/src/UI/MainWindow.xaml.cs).
